In [2]:
#Question 1:

import numpy as np
np.arange(2,51,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

In [17]:
#Question 2:

list1=[int(input()) for i in range(5)]
list2=[int(input()) for i in range(5)]
a=np.array(list1)
b=np.array(list2)
print('array after concatenation:',np.concatenate((a,b)))    
print('sorted array 1:',np.sort(a))
print('sorted array 2:',np.sort(b))

12
3234
12
34
56
23
76
23
43
56
array after concatenation: [  12 3234   12   34   56   23   76   23   43   56]
sorted array 1: [  12   12   34   56 3234]
sorted array 2: [23 23 43 56 76]


In [23]:
#Question 3:

ar=np.array([[2,5,1,22],[23,12,45,20],[23,7,45,89]])
print('dimension:',ar.ndim)
print('array size:',ar.size)

dimension: 2
array size: 12


In [33]:
#Question 4:

ar=np.arange(10)
roar=ar[np.newaxis,:]
print('actual array dimension :',ar.ndim)
print('array dimension after using np.newaxis:',roar.ndim)
ab=np.expand_dims(ar,axis=0)
print('array dimension after using np.expand_dims:',ab.ndim)

actual array dimension : 1
array dimension after using np.newaxis: 2
array dimension after using np.expand_dims: 2


In [36]:
#Question 5:

arr_1 = np.square([1, 12, 4, 3, 6])
arr_2 = np.square([16, 7, 5, 9, 10])
print("Horizontal Append :",np.hstack((arr_1, arr_2)))
print("Vertical Append :",np.vstack((arr_1, arr_2)))

Horizontal Append : [  1 144  16   9  36 256  49  25  81 100]
Vertical Append : [[  1 144  16   9  36]
 [256  49  25  81 100]]


In [45]:
#Question 6:

arr_1 = np.array([1, 4, 9, 16, 25, 1, 4, 2, 3, 2, 5, 6, 5, 7, 8, 10])
unique,counts = np.unique(arr_1, return_counts=True)
print(unique)
print(counts)

[ 1  2  3  4  5  6  7  8  9 10 16 25]
[2 2 1 2 2 1 1 1 1 1 1 1]
